FROM tomcat:10.1-jdk17-temurin

RUN rm -rf /usr/local/tomcat/webapps/ROOT

COPY foodie.war /usr/local/tomcat/webapps/ROOT.war

CMD sed -i "s/port=\"8080\"/port=\"${PORT:-80}\"/" /usr/local/tomcat/conf/server.xml && catalina.sh run
